language: cpp
script:

- cmake -H. -B_build -DCMAKE_INSTALL_PREFIX=_install -DBUILD_EXAMPLES=ON -DCPACK_GENERATOR="TGZ"
- cmake --build _build
- cmake --build _build --target install
- cmake --build _build --target package
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
